name: pr
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  go-lint:
    runs-on: golang:1.19.3-bullseye
    steps:
      - name: Install dependencies
        run: apt update && apt install make git gcc --no-install-recommends

      - name: Run make tidy
        run: make tidy

      - name: Run make dirty
        run: make -B dirty

      - name: Run make vet
        run: make vet

      - name: Run linting
        run: make lint

      - name: Build go
        run: make build
