name: pr
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.3'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          pwd
          ls -la
          git status

      - name: Run go tidy
        run: make tidy

      - name: Run make dirty
        run: make -B dirty

      - name: Run vet & lint
        run: |
          make vet
          make lint

      - name: Build go
        run: make build
